play_top100:
  description: Play top 100 on Zing MP3
  fields:
    entity_id:
      description: Name of the media_player to play
      example: 'media_player.bedroom_speaker'
    category:
      description: 'Pop(default), Country, Rock, Dance, R&B, Rap, Soundtrack, Nhac tre, Tru tinh, Que huong, Cach mang, Rock Viet, Rap Viet, Dance Viet'
      example: 'Nhac tre'
    repeat:
      description: Repeat when completed. Default is false
      example: true
    shuffle:
      description: Shuffle song in playlist. Default is false
      example: true

play:
  description: Search and play song on Zing MP3
  fields:
    entity_id:
      description: media player to play
      example: 'media_player.bedroom_speaker'
    name:
      description: Song name to play
      example: 'happy new year'
